# Generated by Django 3.1 on 2021-01-07 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_dish', to='core.dish'),
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=35)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_dish', to='core.dish')),
            ],
            options={
                'verbose_name': 'Lunch',
                'verbose_name_plural': 'Lunch',
            },
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=35)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_dish', to='core.dish')),
            ],
            options={
                'verbose_name': 'dinner',
                'verbose_name_plural': 'Dinner',
            },
        ),
        migrations.AddField(
            model_name='monday',
            name='dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner', to='core.dinner'),
        ),
        migrations.AddField(
            model_name='monday',
            name='lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='core.lunch'),
        ),
    ]
