# Generated by Django 3.1 on 2021-01-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210107_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monday',
            new_name='Weekly',
        ),
    ]
