# Generated by Django 3.1 on 2021-01-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210107_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekly',
            options={'verbose_name': 'A Week diet', 'verbose_name_plural': 'Week Diet'},
        ),
        migrations.AddField(
            model_name='weekly',
            name='day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
    ]
